#ifndef IR_COMMANDS_H
#define IR_COMMANDS_H

typedef enum IR_COMMANDS {

    // CMD_POWER,
    CMD_TURN_RED,
    CMD_TURN_BLUE,
    CMD_TURN_GREEN,
    // CMD_TURN_MOON,
    // CMD_TURN_STARS,
    // CMD_BRIGHTNESS_UP,
    // CMD_BRIGHTNESS_DOWN,
    // CMD_MODE,

    CMD_COUNT,
} IR_COMMANDS;

#endif